### ISSUE TITLE
Random deletions and changes to value of keys

### ISSUE THREAD

**Issue by LofiMonk** [solvedDev/AnyLanguage#2]
I uploaded my lang file that is English to be translated. I checked the keys and the values. Everything thing seemed to be in order. 
After downloading the translated files and adding them to my project, including the English file that anyLanguage made.
Seems random parts of the file where taken out and some even changed. I noticed a value to one of the keys changed to undefined.

https://github.com/drewcifer/bot-topia/commit/01ecba596ffefd6767bf322b7f59119bc87cf463

you can look at the en_US file and see the diff after adding the files.
For my help file it creates not only text in the wrong places but the layout gets messed up. I've seen videos of my addon in other languages and the few that open their help menu do have translations and that's cool but they are missing the same parts as the English file and the layout of the help menu is messed up in the same way as the English file.
I'm not sure if its a bug or if I'm not using this tool correctly. I would love to get this to work.

**Comment by solvedDev** [comment]
Heyo 👋 
First of all, thanks for the report!
I am currently no longer maintaining this project. I recognize that it's an useful tool but the way users have to use it is annoying. As you might or might not know, I am working on the add-on editor "bridge." to which we plan to bring this functionality automatically upon building projects.
Once I get to re-implement this, I'll take a look at what could explain the issues you're experiencing in the current code base.

**Comment by LofiMonk** [comment]
Oh Thanks. I was unaware this was not maintained. 
**YES!** Thank you so much for your work on Bridge. I wouldn't even bother making addons if it wasn't for bridge. That's a huge relief knowing that it is planned functionality.

**Comment by dadodasyra** [comment]
Sorry for waking up dead bodies but, is there any updates about what you were saying @solvedDev ?

**Comment by solvedDev** [comment]
AnyLanguage is available for bridge. v2 as a compiler plugin :)
